# Generated by Django 4.2 on 2023-05-01 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_evolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
                ('lane', models.CharField(max_length=7)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='database.pokemon')),
            ],
        ),
    ]
