# Generated by Django 4.2 on 2023-05-01 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_buildskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=21)),
                ('description', models.TextField()),
                ('level', models.CharField(max_length=21)),
                ('image', models.TextField()),
                ('in_game_image', models.TextField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='database.pokemon')),
            ],
        ),
    ]
