# Generated by Django 4.2 on 2023-05-01 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillUpgrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
                ('description', models.TextField()),
                ('level', models.CharField(max_length=21)),
                ('image', models.TextField()),
                ('in_game_image', models.TextField()),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_upgrades', to='database.skills')),
            ],
        ),
    ]
