# Generated by Django 4.2 on 2023-05-01 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_skillupgrades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillupgrades',
            old_name='skills',
            new_name='skill',
        ),
    ]
