# Generated by Django 4.2 on 2023-05-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_rename_skills_skillupgrades_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillupgrades',
            name='in_game_image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skillupgrades',
            name='level',
            field=models.CharField(blank=True, max_length=21),
        ),
    ]
