# Generated by Django 4.2 on 2023-05-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_skillupgrades_in_game_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='in_game_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
