# Generated by Django 4.2 on 2023-05-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_skills_in_game_image_alter_skills_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
