# Generated by Django 4.2 on 2023-05-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_evolution_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolution',
            name='level',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
